var num = [1,2,2,33,22,55,444,555];
console.log(num);
num.push (9965);
console.log(num);
num.pop();
console.log(num);
num.pop();
console.log(num);
num.pop();
console.log(num);
var element = num.pop();
console.log(num);
console.log(element);
